"""EHR report generation utilities."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from src.common.models import EHROutput


def _as_rows(ehr: EHROutput):
    return [
        ["Age", str(ehr.patient_demographics.get("age") or "NA")],
        ["Sex", str(ehr.patient_demographics.get("sex") or "NA")],
        ["Prakriti", str(ehr.prakriti_assessment or "NA")],
        ["Encounter ID", str(ehr.encounter_metadata.get("encounter_id") or "NA")],
    ]


def generate_ehr_pdf(ehr: EHROutput, output_path: str):
    """Generate a clinical EHR PDF summary."""
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    doc = SimpleDocTemplate(str(out), pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("<b>AyurYukti — आयुर्युक्ति | Clinical Encounter Record</b>", styles["Title"]))
    story.append(Spacer(1, 10))

    demo_table = Table(_as_rows(ehr), colWidths=[120, 360])
    demo_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.whitesmoke),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ]
        )
    )
    story.append(demo_table)
    story.append(Spacer(1, 10))

    complaints = ehr.chief_complaints or []
    story.append(Paragraph("<b>Chief Complaints</b>", styles["Heading3"]))
    if complaints:
        for item in complaints:
            txt = f"- {item.get('complaint','NA')} | Duration: {item.get('duration','NA')} | Severity: {item.get('severity','NA')}"
            story.append(Paragraph(txt, styles["BodyText"]))
    else:
        story.append(Paragraph("No complaints captured.", styles["BodyText"]))
    story.append(Spacer(1, 8))

    story.append(Paragraph("<b>Diagnosis</b>", styles["Heading3"]))
    diag_rows = [
        ["AYUSH", f"{ehr.ayush_diagnosis.get('code','-')} | {ehr.ayush_diagnosis.get('name','-')}"],
        ["ICD-10", f"{ehr.icd10_diagnosis.get('code','-')} | {ehr.icd10_diagnosis.get('name','-')}"],
    ]
    diag = Table(diag_rows, colWidths=[120, 360])
    diag.setStyle(TableStyle([("GRID", (0, 0), (-1, -1), 0.5, colors.grey)]))
    story.append(diag)
    story.append(Spacer(1, 8))

    story.append(Paragraph("<b>Prescriptions</b>", styles["Heading3"]))
    if ehr.prescriptions:
        rows = [["Formulation", "Dosage", "Frequency", "Duration", "Route", "Instructions"]]
        for p in ehr.prescriptions:
            rows.append(
                [
                    str(p.get("formulation_name", "")),
                    str(p.get("dosage", "")),
                    str(p.get("frequency", "")),
                    str(p.get("duration", "")),
                    str(p.get("route", "")),
                    str(p.get("special_instructions", "")),
                ]
            )
        table = Table(rows, colWidths=[115, 55, 70, 55, 45, 140])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f2f5f9")),
                    ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                ]
            )
        )
        story.append(table)
    else:
        story.append(Paragraph("No prescriptions captured.", styles["BodyText"]))

    story.append(Spacer(1, 8))
    story.append(Paragraph(f"<b>Lifestyle:</b> {', '.join(ehr.lifestyle_advice or []) or 'NA'}", styles["BodyText"]))
    story.append(Paragraph(f"<b>Diet:</b> {', '.join(ehr.dietary_advice or []) or 'NA'}", styles["BodyText"]))
    story.append(Paragraph(f"<b>Yoga:</b> {', '.join(ehr.yoga_advice or []) or 'NA'}", styles["BodyText"]))
    story.append(Paragraph(f"<b>Follow-up:</b> {ehr.follow_up or 'NA'}", styles["BodyText"]))
    story.append(Spacer(1, 14))

    timestamp = datetime.now(timezone.utc).isoformat()
    footer = (
        f"Generated by AyurYukti | AHMIS-Compatible | Confidential | Timestamp: {timestamp}"
    )
    story.append(Paragraph(footer, styles["Italic"]))

    doc.build(story)


def export_ehr_json(ehr: EHROutput, output_path: str):
    """Export AHMIS-compatible JSON representation."""
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "patientDemographics": ehr.patient_demographics,
        "prakritiAssessment": ehr.prakriti_assessment,
        "chiefComplaints": ehr.chief_complaints,
        "examinationFindings": ehr.examination_findings,
        "diagnosis": {"ayush": ehr.ayush_diagnosis, "icd10": ehr.icd10_diagnosis},
        "prescriptions": ehr.prescriptions,
        "lifestyleAdvice": ehr.lifestyle_advice,
        "dietaryAdvice": ehr.dietary_advice,
        "yogaAdvice": ehr.yoga_advice,
        "followUp": ehr.follow_up,
        "metadata": ehr.encounter_metadata,
    }
    out.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
